#!/bin/bash

if [[ $1 ]] ; then
        cat /etc/passwd | grep -v '^#' | grep $1 | awk -F ':' '{print$1,$3,$6}' | column -t
else
        cat /etc/passwd | grep -v '^#' | awk -F ':' '{print$1,$3,$6}' | column -t
fi
